### ISSUE TITLE
Hello!Can I use the command "systemctl start sshd" to "start_command=" in the config file?

### ISSUE THREAD

**Issue by DoubeGe** [jvinet/knock#48]
Hello!Can I use the command "systemctl start sshd" to "start_command=" in the config file? 
I have done it.and use list command in client:
knock ip 7000
knock ip 8000 
knock ip 9000
but it wasn't seccessed to make the server's sshd software runing.
How I should do to make it take effect?

**Comment by DoubeGe** [comment]
I have done it again.And it take effect.Thanks for your project.

**Comment by jvinet** [comment]
Yep, should work.  Try passing your entire port-knock sequence to a
single 'knock' command:

    $ knock ip 7000 8000 9000





On Thu, Oct 27, 2016, at 03:17 AM, DoubeGe wrote:
> Hello!Can I use the command "systemctl start sshd" to "start_command="
> in the config file?
>  I have done it.and use list command in client:
>  knock ip 7000
>  knock ip 8000
>  knock ip 9000
>  but it wasn't seccessed to make the server's sshd software runing.
>  How I should do to make it take effect?
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>


Links:

  1. https://github.com/jvinet/knock/issues/48

**Comment by ibaldonl** [comment]
Maybe this issue should be closed.
