### ISSUE TITLE
[Question] nftables

### ISSUE THREAD

**Issue by noraj** [jvinet/knock#60]
Hello,

Will knockd work if I change value in `start_command` and `stop_command` to use nftables instead of iptables or is knockd designed to work only with iptables?

**Comment by TDFKAOlli** [comment]
Sure, I do call a script in my setup. Works as well like a charm.
I would just make sure to use full path to nftables, to be sure it is found.

**Comment by noraj** [comment]
[BPF](https://www.kernel.org/doc/Documentation/networking/filter.txt)(filter) incoming, I'm not sure if I have to use nftables

**Comment by ibaldonl** [comment]
@noraj maybe you can give an example of what you are using or close this issue, thanks!
