### ISSUE TITLE
knockd doesn't bind to all IPs assigned to an interface

### ISSUE THREAD

**Issue by visit1985** [jvinet/knock#7]
Have the following setup on arch linux using netctl:

    # ip addr show dev enp2s0
    2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
        link/ether 3c:d9:2b:78:d1:fa brd ff:ff:ff:ff:ff:ff
        inet 192.168.178.10/24 brd 192.168.178.255 scope global enp2s0
           valid_lft forever preferred_lft forever
        inet 172.20.178.10/24 brd 172.20.178.255 scope global enp2s0
           valid_lft forever preferred_lft forever
        inet6 fe80::3ed9:2bff:fe78:d1fa/64 scope link 
           valid_lft forever preferred_lft forever

debug log tells:

     ...
     config: interface: enp2s0
     ...
     ethernet interface detected
     Local IP: 192.168.178.10
     Adding pcap expression for door 'opencloseSSH': (dst host 192.168.178.10 and (((tcp dst port...

knockd picks only the first IP assigned to the interface which could be changed randomly on every boot.

**Comment by airwoflgh** [comment]
Will look into fixing this in combination with Issue 21 on my fork.

**Comment by visit1985** [comment]
@airwoflgh I proposed a fix in #17.

**Comment by airwoflgh** [comment]
Great - have merged it in to my fork.

**Comment by airwoflgh** [comment]
Merged and pull request made back into master.
