### ISSUE TITLE
please add tags corresponding to 0.7 point releases

### ISSUE THREAD

**Issue by ddstreet** [jvinet/knock#73]
It seems the current git repo is up to point release 0.7.8, but there are no official releases for any of these nor are there any git tags corresponding to the point releases. Can you please add tags to each git commit point release? Or at least can you add a tag for the 0.7.8 point release?

I ask for this because Debian (and thus Ubuntu and all other Debian derivatives) are still shipping 0.7, and typically only official releases are used; that can be either officially-provided tarball, or even a simple git tag if that's all that is provided.

**Comment by dimkr** [comment]
@ddstreet I agree it would be nice to have a proper release with all the fixes that went into master recently. I'd do it gladly, but I'm not the maintainer of knockd and I prefer not to create yet another fork that lags behind upstream.

**Comment by ddstreet** [comment]
lol, yeah i'm asking you from *both* places! :)

**Comment by dimkr** [comment]
@jvinet ping

**Comment by jvinet** [comment]
0.8 is up now.  Thanks all.
