### ISSUE TITLE
Consider ipv6 

### ISSUE THREAD

**Issue by tigerfoot** [jvinet/knock#8]
With the grow of ipv6 usage it would be cool to have ipv6 support in knock/knockd

See a proposal by debian 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=617369

**Comment by airwoflgh** [comment]
Duncan - could you post referenced patch / a link to it please. Will review and build into my fork.

**Comment by airwoflgh** [comment]
Added this to the TODO list for 0.8.

**Comment by Coksnuss** [comment]
Is there any chance that PR #53 is to be reviewed/merged anytime soon? Currently, when using the knock client for portknocking, SSH must be forced to connect via IPv4 in order to work.

**Comment by TDFKAOlli** [comment]
Also created a pull request for OpenWRT Makefile change (milaq/openwrt_knockd#6) including #52, #53 and #55 and build for OpenWrt 18.06.1.

**Comment by primeos** [comment]
Unfortunately this project seems to be abandoned (last commit at the end of 2015).
